package nanoda

import (
	"github.com/ebitengine/purego"
)

// 関数の紐付けを行う
func (v *Voicevox) register() {
	purego.RegisterLibFunc(&v.voicevoxCreateSupportedDevicesJson, v.core, "voicevox_create_supported_devices_json")
	purego.RegisterLibFunc(&v.voicevoxErrorResultToMessage, v.core, "voicevox_error_result_to_message")
	purego.RegisterLibFunc(&v.voicevoxGetVersion, v.core, "voicevox_get_version")
	purego.RegisterLibFunc(&v.voicevoxJsonFree, v.core, "voicevox_json_free")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerCreateAccentPhrases, v.core, "voicevox_synthesizer_create_accent_phrases")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerCreateAccentPhrasesFromKana, v.core, "voicevox_synthesizer_create_accent_phrases_from_kana")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerCreateAudioQuery, v.core, "voicevox_synthesizer_create_audio_query")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerCreateAudioQueryFromKana, v.core, "voicevox_synthesizer_create_audio_query_from_kana")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerCreateMetasJson, v.core, "voicevox_synthesizer_create_metas_json")
	purego.RegisterLibFunc(&v.voicevoxOpenJtalkRcDelete, v.core, "voicevox_open_jtalk_rc_delete")
	purego.RegisterLibFunc(&v.voicevoxOpenJtalkRcNew, v.core, "voicevox_open_jtalk_rc_new")
	purego.RegisterLibFunc(&v.voicevoxOpenJtalkRcUseUserDict, v.core, "voicevox_open_jtalk_rc_use_user_dict")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerDelete, v.core, "voicevox_synthesizer_delete")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerIsGpuMode, v.core, "voicevox_synthesizer_is_gpu_mode")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerIsLoadedVoiceModel, v.core, "voicevox_synthesizer_is_loaded_voice_model")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerLoadVoiceModel, v.core, "voicevox_synthesizer_load_voice_model")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerNewWithInitialize, v.core, "voicevox_synthesizer_new_with_initialize")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerReplaceMoraData, v.core, "voicevox_synthesizer_replace_mora_data")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerReplaceMoraPitch, v.core, "voicevox_synthesizer_replace_mora_pitch")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerReplacePhonemeLength, v.core, "voicevox_synthesizer_replace_phoneme_length")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerSynthesis, v.core, "voicevox_synthesizer_synthesis")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerTts, v.core, "voicevox_synthesizer_tts")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerTtsFromKana, v.core, "voicevox_synthesizer_tts_from_kana")
	purego.RegisterLibFunc(&v.voicevoxSynthesizerUnloadVoiceModel, v.core, "voicevox_synthesizer_unload_voice_model")
	purego.RegisterLibFunc(&v.voicevoxUserDictAddWord, v.core, "voicevox_user_dict_add_word")
	purego.RegisterLibFunc(&v.voicevoxUserDictDelete, v.core, "voicevox_user_dict_delete")
	purego.RegisterLibFunc(&v.voicevoxUserDictImport, v.core, "voicevox_user_dict_import")
	purego.RegisterLibFunc(&v.voicevoxUserDictLoad, v.core, "voicevox_user_dict_load")
	purego.RegisterLibFunc(&v.voicevoxUserDictNew, v.core, "voicevox_user_dict_new")
	purego.RegisterLibFunc(&v.voicevoxUserDictRemoveWord, v.core, "voicevox_user_dict_remove_word")
	purego.RegisterLibFunc(&v.voicevoxUserDictSave, v.core, "voicevox_user_dict_save")
	purego.RegisterLibFunc(&v.voicevoxUserDictToJson, v.core, "voicevox_user_dict_to_json")
	purego.RegisterLibFunc(&v.voicevoxUserDictUpdateWord, v.core, "voicevox_user_dict_update_word")
	purego.RegisterLibFunc(&v.voicevoxVoiceModelDelete, v.core, "voicevox_voice_model_delete")
	purego.RegisterLibFunc(&v.voicevoxVoiceModelGetMetasJson, v.core, "voicevox_voice_model_get_metas_json")
	purego.RegisterLibFunc(&v.voicevoxVoiceModelId, v.core, "voicevox_voice_model_id")
	purego.RegisterLibFunc(&v.voicevoxVoiceModelNewFromPath, v.core, "voicevox_voice_model_new_from_path")
	purego.RegisterLibFunc(&v.voicevoxWavFree, v.core, "voicevox_wav_free")
}
